/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"main.h"

int main(void)
{
  LED_Init();
  
	while (1)
  {
    LED_On();
    delay();
    LED_Off();
    delay();
  }
  

	return 0;
}

void delay(void){
  for (uint32_t i = 0; i < 500000; i++)
  {
    //Nothing
  }
  
}